# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2108683c26934380de5be52ae20f7a3452e2f85def5c34fe76ca72bae2475325f327e26ae4204c328bb10517ab3ee27bd4ea1664101594fb1443bf27e532e7b2

test:
  secret_key_base: 20cafc02830f21f8a408541d963c6aa5c1fb3be0c95e0b3a886f52d0723f04a3f8117242016b1e23246d73ad421335712c83a810265228df8f96fd1c7cc55bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
